spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/health_care_systems
    password: Suvetha18
server:
  port: '8080'
  
my:
  greeting: Welcome everyone to the grand karigalan magic show!!!
